### ISSUE TITLE
sprites dataset

### ISSUE THREAD

**Issue by panyx0718** [carpedm20/visual-analogy-tensorflow#2]
Hi, I'm trying to use the sprites dataset. Thanks for uploading it.

There are many mat files, such as sprites_200.mat.
I use h5py to read the file.
There are following keys: [u'#refs#', u'labels', u'masks', u'sprites']

I managed to get some numpy arrays from it
 >>> data = [mat[e[0]][:] for e in mat['sprites']]
>>> img = data[10]
>>> img.shape
(9, 10800)
scipy.misc.imsave('/tmp/test_%d.jpg' % i, np.reshape(img_i, [60, 60, 3]))

However, the image is very low resolution and each image contains 9 characters.

Could you advice what's the correct way to open the dataset?

**Comment by carpedm20** [comment]
It's better to open mat file in matlab (which has free trial version) to see the structure of the mat file. I also remember that there was a program that can open mat file by it self without matlab.
